import random  # Module to allow us to generate random characters
import timeit  # Module to help us track the runtime of the function
import string  # Module to help us access ASCII lowercase and uppercase constants when generating random strings
import matplotlib.pyplot as plt  # help us to plot the graph


# Function to convert a string to lower case
def convert_to_lowercase(my_string):
    string_list = list(my_string)  # Converts the string into a list of characters
    return_string = ""   # initialize string to be returned by the function
    for letter in string_list:  # iterates through every character of the string
        return_string += letter.lower()  # append each character after turning it into lower case

    return return_string  # returns the original string but now in lower case


size_array = []  # contains the sizes of all strings that will be generated by the program
runtime_array = []  # Contains all the runtimes of the strings in the program


# Iterates through the numbers from 1 to 100 and increment by 20 after each iteration to determine the string sizes
for string_size in range(1, 100, 20):
    # initializing all the ASCII uppercase constants to a variable
    letters = string.ascii_uppercase
    # Generating a random uppercase characters to form a string of size (string_size) ie. the value of the index in the outer loop
    mystring = ''.join(random.choices(letters, k=string_size))
    start_time = timeit.default_timer()  # Capturing the start time
    # Calling the function to convert to lower case and passing the randomly generated string
    print(f"Lowercase string: {convert_to_lowercase(mystring)}")
    end_time = timeit.default_timer()  # Capturing the end time
    runtime = end_time - start_time  # Calculating the runtime
    size_array.append(string_size)  # appending the size of the string under iteration to the size_array
    runtime_array.append(runtime)  # appending the runtime of the string under iteration to the runtime_array
    print(f"List size: {string_size} --> Runtime: {runtime}")


# plotting the input size(string size) against runtime
plt.plot(size_array, runtime_array)

# naming the x axis
plt.xlabel('Input size')
# naming the y axis
plt.ylabel('Time')

# giving a title to my graph
plt.title('Graph')

# function to show the plot
plt.show()
